/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Database */

#ifndef _Included_Database
#define _Included_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Database
 * Method:    getTableAsJson
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Database_getTableAsJson
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
